spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers: true
        show_sql: false
        format_sql: false
        generate_statistics: true
    defer-datasource-initialization: true
  mvc:
    static-path-pattern: /webapp/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: always
      data-locations: classpath:META-INF/data.sql
  main:
    allow-bean-definition-overriding: true


logging.level:
  org.hibernate.SQL: warn
  org.springframework.web: debug
  org.hibernate.stat: off

driver:
  chrome:
    driver_path: /resources/chromeDriver/chromedriver
